name: Continuous delivery - Windows

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [prereleased, released]
  workflow_dispatch:

jobs:
  version-check:
    name: Check versioning
    runs-on: windows-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install required packages
        run: choco install poetry --source python
      - name: Create virtual envrionment
        run: make init
      - name: Check version tag format
        run: |
          $VERSION_TAG="${{ github.event.release.tag_name }}"
          if ($VERSION_TAG -match "^v[0-9]+.[0-9]+.[0-9]+$") {exit 0} else {exit 1}
      - name: Check if version tag and package version are equal
        run: |
          $VERSION_TAG="${{ github.event.release.tag_name }}"
          $VERSION_PACKAGE=poetry version --short
          if ($VERSION_TAG.Substring(1) -eq $VERSION_PACKAGE) {exit 0} else {exit 1}
  build-onefile:
    name: Build Windows Onefile
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install required packages
        run: choco install poetry --source python
      - name: Create virtual environment
        run: poetry install
      - name: Create Windows version info file
        run: |
          poetry run create-version-file `
            --outfile .\ci-scripts\windows\pyinstaller\file_version_info.txt `
            --version "$(poetry version --short)" `
            .\ci-scripts\windows\pyinstaller\file_version_info_metadata.yaml
      - name: Build onefile
        run: |
          poetry run pyinstaller ci-scripts/windows/pyinstaller/nitrokey-app-onefile.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: nitrokey-app-onefile
          path: dist/nitrokey-app.exe

  publish-binary:
    name: Publish Windows Binary
    runs-on: windows-latest
    needs: build-onefile
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: nitrokey-app-onefile
          path: binary-out  # Expliziter Pfad um Verwirrung zu vermeiden
      - name: Rename and Publish
        shell: pwsh
        run: |
          Move-Item "binary-out\nitrokey-app.exe" "nitrokey-app-${{ github.event.release.tag_name }}-x64-windows-binary.exe"
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: nitrokey-app-${{ github.event.release.tag_name }}-x64-windows-binary.exe
